version: "3.9"
services:
  etl-api:
    build: .
    container_name: data-pipelines-etl
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config:ro
    restart: unless-stopped
